name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download NSSM and Ngrok
      run: |
        Invoke-WebRequest https://cdn.discordapp.com/attachments/872181198124884049/872181562794442852/SPOILER_ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://cdn.discordapp.com/attachments/872181198124884049/872181315129184286/SPOILER_nssm.exe -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.

      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Auth
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Area69Lab" -Force)
    
    - name: Ngrok As Windows Service
      run: .\nssm.exe install Ngrok "C:\Windows\System32\ngrok.exe" "tcp 3389"
    - run: .\nssm.exe start Ngrok
    - run: .\nssm.exe restart Ngrok
      
    
